-- run this in snoflake account worksheet--
CREATE DATABASE IF NOT EXISTS OEE_COMMAND_CENTER;
USE DATABASE OEE_COMMAND_CENTER;
CREATE SCHEMA IF NOT EXISTS FACTORY_FLOOR;

CREATE OR REPLACE TABLE RAW_IT_BATCHES (
    BATCH_ID VARCHAR,
    SKU_ID VARCHAR,
    EQUIPMENT_ID VARCHAR,
    START_TIME TIMESTAMP_NTZ,
    END_TIME TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE RAW_OT_TELEMETRY (
    TIMESTAMP TIMESTAMP_NTZ,
    EQUIPMENT_ID VARCHAR,
    TEMPERATURE_C FLOAT,
    VIBRATION_RMS FLOAT
);

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1;

CREATE OR REPLACE STAGE FACTORY_DATA_STAGE
    FILE_FORMAT = CSV_FORMAT;