--transforms the isolated streams into a converged state--
CREATE OR REPLACE DYNAMIC TABLE IT_OT_CONVERGED
    TARGET_LAG = '1 minute'
    WAREHOUSE = 'COMPUTE_WH'
AS
SELECT
    ot.TIMESTAMP,
    ot.EQUIPMENT_ID,
    ot.TEMPERATURE_C,
    ot.VIBRATION_RMS,
    COALESCE(it.BATCH_ID, 'CHANGEOVER/IDLE') AS BATCH_ID,
    COALESCE(it.SKU_ID, 'NONE') AS SKU_ID
FROM RAW_OT_TELEMETRY ot
LEFT JOIN RAW_IT_BATCHES it
    ON ot.EQUIPMENT_ID = it.EQUIPMENT_ID
    AND ot.TIMESTAMP BETWEEN it.START_TIME AND it.END_TIME;