USE DATABASE OEE_COMMAND_CENTER;
USE SCHEMA FACTORY_FLOOR;

CREATE OR REPLACE TABLE OEM_MANUAL_CHUNKS AS
SELECT
    RELATIVE_PATH AS FILE_NAME,
    c.INDEX AS CHUNK_INDEX,
    c.VALUE::STRING AS CHUNK_TEXT
FROM DIRECTORY(@OEM_MANUALS_STAGE),
LATERAL FLATTEN(
    INPUT => SNOWFLAKE.CORTEX.SPLIT_TEXT_RECURSIVE_CHARACTER(
        TO_VARCHAR(
            AI_PARSE_DOCUMENT(
                TO_FILE('@OEM_MANUALS_STAGE', RELATIVE_PATH),
                OBJECT_CONSTRUCT('mode', 'LAYOUT')
            ):content
        ),
        'markdown',
        2000,
        300
    )
) c
WHERE LOWER(RELATIVE_PATH) LIKE '%.pdf';